### ISSUE TITLE
Página de apoio ao evento

### ISSUE THREAD

**Issue by soapdog** [amora-labs/evento-addons-hackday-2017#2]
# Objetivo
Criação de página com material de referência para o evento. Com a seguinte informação:

- [ ] Documentação de WebExtension da MDN / Mozilla
- [ ] Documentação de WebExtension do Google Chrome
- [ ] Links para os browsers
- [ ] Código de exemplo de diversas extensões

## Observações
O material deve estar preferencialmente em Português. Talvez seja necessário um esforço para traduzir/atualizar material da MDN antes do evento.

**Comment by soapdog** [comment]
Estou pensando em colocar os Addons aqui no github com link para ca na página do meetup em vez de fazer uma página nova do zero.

**Comment by luiguild** [comment]
acho que seria uma boa colocar tudo lá no meetup, é mais rápido

**Comment by guilhermemarconi** [comment]
E deixarmos site para possíveis futuros eventos, com mais tempo para planejar, etc.

Por esse evento ainda ser um piloto, não acho que tenha necessidade de fazermos site.

**Comment by soapdog** [comment]
@luiguild quero colocar pelo menos os addons de exemplo nesse repo aqui, para ficar fácil de clonar.

**Comment by guilhermemarconi** [comment]
@soapdog bom que a gente deixa aqui e a galera forka o que quiser contribuir

**Comment by soapdog** [comment]
Uhum e fica fácil de rodar como exemplo tb

**Comment by soapdog** [comment]
Repositório de exemplos de WebExtensions da mozilla: https://github.com/mdn/webextensions-examples acho que vale o fork e tradução dos comentários.

**Comment by soapdog** [comment]
Aprendendo a rodar WebExtensions com o [web-ext](https://github.com/mozilla/web-ext).

**Comment by soapdog** [comment]
Comecei a tradução dos comentários no repo de addon. Fiz um fork em https://github.com/amora-labs/webextensions-examples/tree/localization-portuguese

**Comment by soapdog** [comment]
Terminei a tradução (meia boca) de todas as extensões menos as:
* embedded-* pois elas são para quem ta trabalhando com port
* native-messaging: pois lida com coisas complicadas de apps nativos

A tradução poderia estar melhor mas já vai ajudar quem não sabe Ingles direito.
