### ISSUE TITLE
Selecionar WebExtensions de exemplo

### ISSUE THREAD

**Issue by soapdog** [amora-labs/evento-addons-hackday-2017#5]
# Objetivo
Achar pelo menos **quatro** WebExtensions de exemplo para o dia do evento. 

## Observações
A página de apoio ao evento #2 poderá listar mais Addons de exemplo, mas esses são os que vamos falar a respeito na parte expositiva do evento.

**Comment by soapdog** [comment]
Sugestão: **Bullshide** do @luiguild

**Comment by guilhermemarconi** [comment]
Sugestão: **[NOPE](https://chrome.google.com/webstore/detail/nope-cant-right-now/hkalleiiedmagdcjgjpciedfeojjlikm)**

**Comment by guilhermemarconi** [comment]
Sugestão: **[Strict Workflow](https://github.com/fafk/Strict-Workflow)**

**Comment by guilhermemarconi** [comment]
Sugestão: **[Tab Wrangler](https://github.com/jacobSingh/tabwrangler)**

**Comment by soapdog** [comment]
@guilhermemarconi esse strick workflow é um fork, o link original é [esse aqui](https://github.com/matchu/Strict-Workflow), não sei a diferença entre os dois, depois olhamos.

**Comment by guilhermemarconi** [comment]
@soapdog verdade, nem reparei. eu busquei no patopatovai e esse foi o primeiro que achou. mas aí a gente vê! 😁

**Comment by luiguild** [comment]
tem aquele que o torto fez que troca o nome do temer por golpista também

**Comment by guilhermemarconi** [comment]
Se parar para pensar, esse addon é bem simples. Mas será que teremos devs de direita no evento? 🙄

**Comment by luiguild** [comment]
podemos usar o addon como exemplo a nível de código só, o que ele faz é consequencia ><

**Comment by guilhermemarconi** [comment]
Rapaz, do jeito que polarizou esse debate por aqui... não me surpreeenderia se rolassem cenas lamentáveis caso houvesse algum conflito referente a isso.

Mas entendo seu ponto! Não precisamos nos posicionar: só dizer que tem esse addon que faz isso e life goes on 🙄

**Comment by soapdog** [comment]
Pois é não vamos usar esse addons não, imagina, treta já no início do evento... climão...
