### ISSUE TITLE
Preparação do varal de idéias

### ISSUE THREAD

**Issue by soapdog** [amora-labs/evento-addons-hackday-2017#8]
# Objetivo
O evento terá um varal com idéias de WebExtensions penduradas. Essas ideias terão uma ilustração a mão (boneco de palitinho fofinho), a descrição do Addon e APIs relacionadas.

Qualquer um poderá pegar uma ideia do varal para implementar. Durante a fase de brainstorm do evento iremos apresentar o varal.

- [x] Conseguir ideias para o varal
- [x] Criar os laminados para pendurar
- [x] Conseguir uma corda/cabo de aço para pendurarmos os laminados

**Comment by luiguild** [comment]
***Ideia de Addon***
Fixar conversas no topo - WhatsApp Web

***Descrição rápida***
Permitir que o usuário fixe conversas específicas na lista do WhatsApp Web. Funcionalidade similar ao Telegram.

***API's específicas necessárias***
Localstorage / LocalForage

***Nível de complexidade***
🍕🍕🍕🍕

**Comment by guilhermemarconi** [comment]
Não sei onde seria o melhor lugar para separarmos essas ideias antes do evento, tendo em dia que irão especificamente para o varal.

Seria legal definirmos um canal para isso e mandar por e-mail para a galera que tiver ideias nos mandar por esse canal e nós botamos essas ideias no varal.

**Comment by luiguild** [comment]
***Ideia de Addon***
Adicionar camada de segurança e confirmação sobre imagens para prevenir NSFW - WhatspApp Web

***Descrição rápida***
O WhatsApp Web aparentemente não respeita as configurações do telefone e faz download de imagens mesmo o usuário não permitindo. O addon deve proteger o usuário de mensagens contendo fotos e vídeos que possam ser de conteúdo inapropriado. Deverá ser exibida uma camada sob o bloco multimídia fazendo com que o usuário clique sobre ele para que a imagem seja liberada para visualização. Uma possibilidade legal de design é utilizar uma camada com Blur para a interface não ser prejudicada.

***API's específicas necessárias***


***Nível de complexidade***
🍕

**Comment by luiguild** [comment]
***Ideia de Addon***
Botão+popup para criação de Gist no GitHub

***Descrição rápida***
Ao clicar sob o botão, um popup seria aberto com o editor de Gist do GitHub para que os devs possam gerar Gist's automaticamente de forma rápida

***API's específicas necessárias***
GitHub?

***Nível de complexidade***
🍕🍕

**Comment by luiguild** [comment]
@guilhermemarconi eu joguei aqui, mas podemos mover pra outro local depois sim 😃

**Comment by guilhermemarconi** [comment]
Parando para pensar, não tem necessidade de nenhum canal específico pra isso, já que no fim das contas será público! 😉 

Melhor deixar por aqui mesmo 😄

**Comment by guilhermemarconi** [comment]
@luiguild sobre essa ideia do Gist, achei [esse repo](https://github.com/github-tools/github) 😄

**Comment by luiguild** [comment]
Sensacional!

**Comment by luiguild** [comment]
***Ideia de Addon***
Notificação extra e marcação em conversas no WhatsApp Web

***Descrição rápida***
Um dos grandes problemas de grupos grandes é quando silenciamos pra não sermos incomodados, porém, quando alguém menciona algo útil ou que te interesse, ou até mesmo fala seu nome, você não consegue acompanhar no meio de tantas mensagens... A ideia é que a mensagem seja marcada com uma cor diferente e que uma notificação seja disparada pelo browser para avisar que algum conteúdo relevante foi dito

***API's específicas necessárias***
Notification, Regex

***Nível de complexidade***
🍕🍕🍕🍕

**Comment by luiguild** [comment]
***Ideia de Addon***
Facebook Light

***Descrição rápida***
Remover uma quantidade enorme de lixo visual do Facebook, dando mais espaço e ênfase para a timeline, diminuindo consideravelmente o número de publicidades e requests a mais que o facebook faz o tempo inteiro... Um ganho considerável de performance e consumo de banda

![captura de tela 2017-03-10 as 11 43 59](https://cloud.githubusercontent.com/assets/16566338/23799381/23de0538-0587-11e7-957a-c385dec5aa35.png)

***API's específicas necessárias***


***Nível de complexidade***
🍕

**Comment by soapdog** [comment]
Essas ideias estão ótimas!

**Comment by soapdog** [comment]
### Ideia de Addon
Anotação básica local

### Descrição rápida
Um addon que permite ao usuário fazer anotações pessoais sobre a página atual. Essas anotações poderiam conter screenshots e texto em markdown. Pode ser parecido com o que o vivaldi faz se conseguirmos injetar uma sidebar.

![Anotação no vivaldi](https://vivaldi.com/assets/notes_screenshot_windows.jpg)

### API's específicas necessárias
IndexedDB/LocalStorage

### Nível de complexidade
🍕🍕🍕🍕

**Comment by soapdog** [comment]
### Ideia de Addon
Navegação por teclado

### Descrição rápida
Fornecer uma forma de navegar rapidamente pela página atual usando o teclado. Algo como um novo [gleeBox](https://addons.mozilla.org/en-US/firefox/addon/gleebox/?src=search) _(parece q existe uma versão mais nova para o chrome)_

### API's

### Nível de complexidade
🍕🍕🍕🍕

**Comment by soapdog** [comment]
### Ideia de Addon
Hub para a página de "New Tab ou Home"

### Descrição rápida
Hub que substitui a página de nova aba ou home com informações de agenda, redes sociais e github de um usuário. 

### APIs
* Redes Sociais
* WebWorkers
* IndexedDB

### Complexidade
🍕🍕🍕🍕

**Comment by soapdog** [comment]
### Ideia de Addon
Foco

### Descrição rápida
Bloqueia certos dominios durante o horário de trabalho. Coisa tipo:
* Facebook
* UOL
* Gizmodo

### APIs

### Complexidade
🍕

**Comment by soapdog** [comment]
### Ideia de Addon
Fingir que é outro navegador

### Descrição rápida
Um popup que permite vc escolher um novo navegador e então trocar o user-agent que o browser está usando naquela aba.

### APIs
[webRequest](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Intercept_HTTP_requests)

### Complexidade
🍕

**Comment by soapdog** [comment]
### Ideia de Addon

Troca o background da página por um pano de fundo relacionado a um time de futebol

### Descrição rápida

Troca o pano de fundo de uma página por uma imagem/padrão relacionado a um time de futebol. Salva as alterações em um cookie.

Basicamente uma versão de [cookie-bg-picker](https://github.com/amora-labs/webextensions-examples/tree/localization-portuguese/cookie-bg-picker)

### APIs

* [Cookies API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies) para salvar / recuperar / remover os cookies.
* [Tabs API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs) para obter informações sobre a guia atual (sempre que uma nova URL é carregada e em cada ponto significativo depois disso ), Injetar o script de conteúdo nela e enviar mensagens entre o script de ação / fundo do navegador eo script de conteúdo.
* [API de tempo de execução](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime) para receber e manipular mensagens enviadas para o script de conteúdo.

### Complexidade
🍕
